url: https://ercanertan.github.io
baseurl:

# Site settings
title: Mr. Ertan Ercan
email:
description: "Full Stack Web Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
  - title: github
    url: https://github.com/ercanertan
avatar: profile.png
# Postal address (add as many lines as necessary)
address:
  - line: SW15 London

# Build settings
markdown: kramdown
permalink: pretty